In [9]:
import pandas as pd
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder

In [6]:
!pip install pandas numpy scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (1.26.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [10]:
import seaborn as sns
# Tải dữ liệu Titanic từ seaborn
data = sns.load_dataset('titanic')
print(data.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

In [11]:
# Loại bỏ các cột không cần thiết như 'embarked' và 'alive'
data = data.drop(columns=['embarked', 'alive'])
print(data.head())

   survived  pclass     sex   age  sibsp  parch     fare  class    who  \
0         0       3    male  22.0      1      0   7.2500  Third    man
1         1       1  female  38.0      1      0  71.2833  First  woman
2         1       3  female  26.0      0      0   7.9250  Third  woman
3         1       1  female  35.0      1      0  53.1000  First  woman
4         0       3    male  35.0      0      0   8.0500  Third    man

   adult_male deck  embark_town  alone
0        True  NaN  Southampton  False
1       False    C    Cherbourg  False
2       False  NaN  Southampton   True
3       False    C  Southampton  False
4        True  NaN  Southampton   True

In [12]:
# Kiểm tra giá trị thiếu
print(data.isnull().sum())
# Điền giá trị thiếu cho các cột số bằng giá trị trung bình
data['age'].fillna(data['age'].mean(), inplace=True)
# Điền giá trị thiếu cho các cột phân loại bằng giá trị phổ biến nhất
data['deck'].fillna(data['deck'].mode()[0], inplace=True)
print(data.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
class            0
who              0
adult_male       0
deck           688
embark_town      2
alone            0
dtype: int64
survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
class          0
who            0
adult_male     0
deck           0
embark_town    2
alone          0
dtype: int64

<ipython-input-12-74d7032f1665>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['age'].fillna(data['age'].mean(), inplace=True)
<ipython-input-12-74d7032f1665>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['deck'].fillna(data['deck'].mode()[0], inplace=True)

In [13]:
# Mã hóa cột 'sex' bằng Label Encoding
label_encoder = LabelEncoder()
data['sex'] = label_encoder.fit_transform(data['sex'])
# Mã hóa cột 'class' bằng One-Hot Encoding
data = pd.get_dummies(data, columns=['class'])
print(data.head())

   survived  pclass  sex   age  sibsp  parch     fare    who  adult_male deck  \
0         0       3    1  22.0      1      0   7.2500    man        True    C
1         1       1    0  38.0      1      0  71.2833  woman       False    C
2         1       3    0  26.0      0      0   7.9250  woman       False    C
3         1       1    0  35.0      1      0  53.1000  woman       False    C
4         0       3    1  35.0      0      0   8.0500    man        True    C

   embark_town  alone  class_First  class_Second  class_Third
0  Southampton  False        False         False         True
1    Cherbourg  False         True         False        False
2  Southampton   True        False         False         True
3  Southampton  False         True         False        False
4  Southampton   True        False         False         True

In [15]:
# Chia dữ liệu thành X (đặc trưng) và y (nhãn)
X = data.drop(columns=['survived'])
y = data['survived']
# Chia thành tập huấn luyện và kiểm tra
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
random_state=42)

In [16]:
# Chuẩn hóa dữ liệu bằng StandardScaler
scaler = StandardScaler()
X_train[['age', 'fare']] = scaler.fit_transform(X_train[['age', 'fare']])
X_test[['age', 'fare']] = scaler.transform(X_test[['age', 'fare']])

In [17]:
# Tạo đặc trưng mới: tỷ lệ giá vé / tuổi
X_train['fare_per_age'] = X_train['fare'] / (X_train['age'] + 1)
X_test['fare_per_age'] = X_test['fare'] / (X_test['age'] + 1)